language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
os:
  - linux
install:
  - pip install --upgrade six
  - pip install .
  - pip install -r requirements/requirements-dev.txt
script: pytest --cov=peppy
branches:
  only:
    - dev
    - master
